title: Carlos Franzreb
description: Personal blog
author: "Carlos Franzreb"

theme: minima

base_url: /
repository: carlosfranzreb/carlosfranzreb.github.io
permalink: /:title

# Minima social links
email: carlos.franzreb@dfki.de
github_username: carlosfranzreb
linkedin_username: carlos-franzreb #-77865037a
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md

include:
  - _pages

exclude:
  - .gitignore
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
